# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET {{host-url}}/ticket/all

###

POST {{host-url}}/ticket
Content-Type: application/json

{
  "id": "7604afd6-7ae8-406e-b4fa-f929cd844b52",
  "seat": 54,
  "tea": true,
  "price": 300
}
###

DELETE {{host-url}}/ticket/7604afd6-7ae8-406e-b4fa-f929cd844b52